# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.4.20"
kotlinxSerializationJSON = "1.9.0"
kotlinxCoroutines = "1.10.2"

angusMail = "2.0.5"
msal4j = "1.23.1"
googleOAuthClient = "1.39.0"
dotenv = "3.2.0"
slf4j = "2.0.17"
slf4jSimple = "2.0.17"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

angusMail = { module = "org.eclipse.angus:angus-mail", version.ref = "angusMail" }

msal4j = { module = "com.microsoft.azure:msal4j", version.ref = "msal4j" }
googleOAuthClientJetty = { module = "com.google.oauth-client:google-oauth-client-jetty", version.ref = "googleOAuthClient" }

dotenv = { module = "io.github.cdimascio:dotenv-java", version.ref = "dotenv" }

slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4jSimple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4jSimple" }
